name = "SchlierenReconstructions"
uuid = "390ecd65-f8fc-464d-8e27-ad19addf2976"
authors = ["Masahito Akamine <akamine502@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
